---
title: "Codebook Package Comparison"
output: html_document
---

<br>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

```{r, echo = FALSE}

yes <- emo::ji("check")

no <- emo::ji("x")

tibble::tribble(
  ~`Variable Metric`, ~`codebook::codebook()`, ~`memisc::codebook()`, ~`sjPlot::view_df()`,
  ~`labelled::generate_dictionary()`, ~ `dataReporter::makeDataReport()`,~`Variable Metric2`, 
  ~ `skimr::skim()`, 
  ~ `pointblank::scan_data()`, ~ `summarytools::dfSummary()`, 
  ~ `gtsummary::tbl_summary()`, ~ `codebookr::codebook()`, ~ `datawizard::data_codebook()`,
  "Name", yes, yes, yes, yes, yes, "Name", yes, yes, yes, yes, yes, yes,
  "Label", yes, yes, yes, yes, yes, "Label", no, no, yes, yes, yes, yes,
  "Type", yes, yes, yes, yes, yes, "Type", no, no, yes, no, yes, yes,
  "Values", yes, yes, yes, yes, no, "Values", no, no, yes, yes, yes, yes,
  "Value labels", yes, yes, yes, yes, no, "Value labels", no, no, no, no, yes, yes,
  "NA values", yes, yes, yes, no, no, "NA values", no, no, no, yes, yes, yes, 
  "NA labels", yes, yes, yes, no, no, "NA labels", no, no, no, no, yes, yes,
  "Total valid N", no, no, no, no, no, "Total valid N", no, no, yes, yes, no, no,
  "Total missing N", yes, no, yes, no, yes, "Total missing N", yes, yes, yes, yes, no, yes,
  "N per value", yes, yes, yes, no, no, "N per value", yes, no, yes, yes, yes, yes,
  "% per value", no, yes, yes, no, no, "% per value", no, no, yes, yes, yes, no,
  "N per NA value", no, yes, yes, no, no, "N per NA value", no, no, no, yes, yes, yes,
  "% per NA value" , no, yes, yes, no, no, "% per NA value", no, no, no, yes, yes, no,
  "Range for continuous", yes, yes, yes, no, yes, "Range for continuous", yes, yes, yes, yes, yes, yes,
  "Mean for continuous", yes, yes, no, no, no, "Mean for continuous", no, yes, yes, yes, yes, no
) %>% 
  relocate(`codebookr::codebook()`, .before = `codebook::codebook()`) %>%
  gt::gt() %>%
  gt::cols_align(align = "left", columns = 'Variable Metric') %>%
  gt::cols_label(`Variable Metric` = "Variable\nMetric", 
                 `codebook::codebook()` = "codebook::\ncodebook()",
               `memisc::codebook()` = "memisc::\ncodebook()" , 
               `sjPlot::view_df()` = "sjPlot::\nview_df()", 
               `labelled::generate_dictionary()` = "labelled::\ngenerate_dictionary()",
               `dataReporter::makeDataReport()` = "dataReporter::\nmakeDataReport()",
               `Variable Metric2` = "Variable\nMetric",
               `skimr::skim()` = "skimr::\nskim()", 
               `pointblank::scan_data()` = "pointblank::\nscan_data()", 
               `summarytools::dfSummary()` = "summarytools::\ndfSummary()", 
               `gtsummary::tbl_summary()` = "gtsummary::\ntbl_summary()",
              `codebookr::codebook()` = "codebookr::\ncodebook()", 
              `datawizard::data_codebook()` = "datawizard::\ndata_codebook()"
               )

```

<br>

*Note: `dataMaid` has been renamed to `dataReporter`. You can read more about it [here](https://github.com/ekstroem/dataMaid).  
\*Note: I am currently working through a few errors I have run into with the `datawizard::data_codebook()` function. I will update as I learn more.

```{r, eval = FALSE, include=FALSE, echo = FALSE}

yes <- emo::ji("check")

no <- emo::ji("x")

tibble::tribble(
  ~`Variable Metric`, ~`codebook::codebook()`, ~`memisc::codebook()`, ~`sjPlot::view_df()`,
  ~`codebookr::codebook()`,
  "Name", yes, yes, yes, yes,
  "Label", yes, yes, yes, yes,
  "Type", yes, yes, yes, yes,
  "Values", yes, yes, yes, yes,
  "Value labels", yes, yes, yes, yes,
  "NA values", yes, yes, yes, yes,
  "NA labels", yes, yes, yes, yes,
  "Total valid N", no, no, no, no,
  "Total missing N", yes, no, yes, no,
  "N per value", yes, yes, yes, yes,
  "% per value", no, yes, yes, yes,
  "N per NA value", no, yes, yes, yes,
  "% per NA value" , no, yes, yes, yes,
  "Range for continuous", yes, yes, yes, yes,
  "Mean for continuous", yes, yes, no, yes
) %>% 
  relocate(`codebookr::codebook()`, .before = `codebook::codebook()`) %>%
  gt::gt() %>%
  gt::cols_align(align = "left", columns = 'Variable Metric') %>%
  gt::cols_label(`Variable Metric` = "Variable\nMetric", 
                 `codebook::codebook()` = "codebook::\ncodebook()",
               `memisc::codebook()` = "memisc::\ncodebook()" , 
               `sjPlot::view_df()` = "sjPlot::\nview_df()", 
               `codebookr::codebook()` = "codebookr::\ncodebook()")

```
